Script started on 2016年03月14日 (週一) 20時37分30秒
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ whoami;pe[Kws[Kd
F74046161
/home/F74046161
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ git config -l
user.name=Happyfishhhy
user.mail=s1171148493@gmail.com
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ git clone 
You must specify a repository to clone.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ https://github.com/happyfishhhy/lab1.git
bash: https://github.com/happyfishhhy/lab1.git: No such file or directory
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ 
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ git clone 
You must specify a repository to clone.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ https://github.com/happyfishhhy/lab1.git
bash: https://github.com/happyfishhhy/lab1.git: No such file or directory
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ 
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ git clone https://github.com/happyfishhhy/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ ls
[0m[01;34mlab1[0m  lab1.script
]0;F74046161@2015cpp: ~F74046161@2015cpp:~$ exit

Script done on 2016年03月14日 (週一) 20時39分47秒
